"""change for less ambiguity

Revision ID: 85804dfad293
Revises: bd9db605fd9b
Create Date: 2026-04-30 11:17:01.852034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85804dfad293'
down_revision: Union[str, Sequence[str], None] = 'bd9db605fd9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('complaints', sa.Column('solved_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('complaints', sa.Column('approved_by', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('complaints_user_id_fkey'), 'complaints', type_='foreignkey')
    op.create_foreign_key(None, 'complaints', 'users', ['approved_by'], ['id'])
    op.drop_column('complaints', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('complaints', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'complaints', type_='foreignkey')
    op.create_foreign_key(op.f('complaints_user_id_fkey'), 'complaints', 'users', ['user_id'], ['id'])
    op.drop_column('complaints', 'approved_by')
    op.drop_column('complaints', 'solved_at')
    # ### end Alembic commands ###
