"""add user kelurahan relationship

Revision ID: bd9db605fd9b
Revises: 34169c654b43
Create Date: 2026-04-28 22:28:40.154477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd9db605fd9b'
down_revision: Union[str, Sequence[str], None] = '34169c654b43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_kelurahans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('kelurahan_name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_kelurahans_id'), 'user_kelurahans', ['id'], unique=False)
    op.create_index(op.f('ix_user_kelurahans_kelurahan_name'), 'user_kelurahans', ['kelurahan_name'], unique=False)
    op.add_column('complaints', sa.Column('category', sa.String(), nullable=True))
    op.drop_column('users', 'kelurahan_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('kelurahan_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('complaints', 'category')
    op.drop_index(op.f('ix_user_kelurahans_kelurahan_name'), table_name='user_kelurahans')
    op.drop_index(op.f('ix_user_kelurahans_id'), table_name='user_kelurahans')
    op.drop_table('user_kelurahans')
    # ### end Alembic commands ###
